apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-producer.fullname" . }}-secrets
  labels:
    {{- include "test-producer.labels" . | nindent 4 }}
type: Opaque
stringData:
  event-hub-connection-string: {{ .Values.secrets.eventHubConnectionString | quote }}

